#用来测试远程配置的文件
spring:
  rabbitmq:
    host: localhost
    port: 15672
    username: "guest"
    password: "guest"
server:
  port: 8763
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8111/eureka/
person:
 name: hs_nb
 age: 25
 like: "writing,reading"
 job:
  type: "IT"
  address: "chengDu,SiChuan"

